// <auto-generated />
using GuildManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(GuildManagerDbContext))]
    [Migration("20220813091335_AddGuildConfigurations")]
    partial class AddGuildConfigurations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("GuildManager.AdminRole", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildConfigurationDiscordGuildId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildConfigurationDiscordGuildId");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("GuildManager.GuildConfiguration", b =>
                {
                    b.Property<string>("DiscordGuildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildWarsApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildWarsGuildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordGuildId");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("GuildManager.AdminRole", b =>
                {
                    b.HasOne("GuildManager.GuildConfiguration", null)
                        .WithMany("AdminRoles")
                        .HasForeignKey("GuildConfigurationDiscordGuildId");
                });

            modelBuilder.Entity("GuildManager.GuildConfiguration", b =>
                {
                    b.Navigation("AdminRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
